// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://feebrdhycyzufgtefvjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlZWJyZGh5Y3l6dWZndGVmdmpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3MTM1NzIsImV4cCI6MjA1MzI4OTU3Mn0._s6m9_s33192PaFxvTkABw3-3ycK_FrHTwhItVi6gm8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);